repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 0.7.1
    hooks:
      # Run the linter.
      - id: ruff
        args: [--fix]
      # Run the formatter.
      - id: ruff-format
