exclude = ["tests", "utils", "third-party"]

line-length = 120

[lint]
preview = true
select = ["E20", "E21", "E22", "E23", "E24", "E3", "F401", "F8"]

[lint.per-file-ignores]
"stock-plugins/aiverify.stock.veritas/algorithms/veritastool/*" = ["F841"]
