version: '3.8'

name: aiverify
services:
  apigw: # required for all services
    build:
      context: ../../
      dockerfile: aiverify-apigw/Dockerfile
    # profiles: [frontend,automated_tests]
    ports:
      - "4000:4000"
    volumes:
      - apigw_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/docs"]
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      APIGW_LOG_LEVEL: "debug"
      APIGW_DATA_DIR: "/data"
      APIGW_HOST_ADDRESS: "0.0.0.0"
      VALKEY_HOST_ADDRESS: valkey
    networks:
      - aiverify_net

  portal:
    build:
      context: ../../
      dockerfile: aiverify-portal/Dockerfile
      target: development
    profiles:
      - portal
    depends_on:
      - apigw
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
    ports:
      - "3000:3000"
    environment:
      APIGW_HOST: "http://host.docker.internal:4000"
      NEXT_PUBLIC_APIGW_HOST: "http://127.0.0.1:4000"
    networks:
      - aiverify_net

  valkey:
    image: valkey/valkey:8
    profiles:
      - automated-tests-venv
      - automated-tests-docker
    healthcheck:
      test: ["CMD", "valkey-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    ports:
      - '6379:6379'
    networks:
      - aiverify_net

  test-engine-worker-base:
    image: aiverify-test-engine-worker-base
    build:
      context: ../../
      dockerfile: aiverify-test-engine-worker/Dockerfile
      target: aiverify-test-engine-worker-base
    profiles:
      - build-only
    networks:
      - aiverify_net

  test-engine-worker:
    build:
      context: ../../
      dockerfile: aiverify-test-engine-worker/Dockerfile
      target: venv-build
    profiles:
      - automated-tests-venv
    deploy:
      mode: replicated
      replicas: 3
    depends_on:
      # - test-engine-worker-base
      - valkey
    environment:
      TEWORKER_LOG_LEVEL: "debug"
      APIGW_URL: http://apigw:4000
      VALKEY_HOST_ADDRESS: valkey
      PIPELINE_BUILD: virtual_env
      PIPELINE_EXECUTE: virtual_env_execute
    networks:
      - aiverify_net

  test-engine-worker-docker:
    user: root
    build:
      context: ../../
      dockerfile: aiverify-test-engine-worker/Dockerfile
      target: docker-build
    profiles:
      - automated-tests-docker
    deploy:
      mode: replicated
      replicas: 3
    depends_on:
      - valkey
    environment:
      TEWORKER_LOG_LEVEL: "debug"
      APIGW_URL: http://apigw:4000
      VALKEY_HOST_ADDRESS: valkey
      PIPELINE_BUILD: docker_build
      PIPELINE_EXECUTE: docker_run
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    networks:
      - aiverify_net

volumes:
  apigw_data:
    driver: local

networks:
  aiverify_net:
    driver: bridge
