import { IconName } from '.';

export const lineIcons = [
  IconName.Alert,
  IconName.ArrowRight,
  IconName.ArrowLeft,
  IconName.Pencil,
  IconName.Asterisk,
  IconName.Book,
  IconName.BurgerMenu,
  IconName.ChatBubbleWide,
  IconName.ChatBubbles,
  IconName.CircleArrowRight,
  IconName.CircleArrowLeft,
  IconName.Close,
  IconName.Document,
  IconName.File,
  IconName.LayoutColumns,
  IconName.LayoutWtf,
  IconName.LightSun,
  IconName.List,
  IconName.Maximize,
  IconName.Minimize,
  IconName.OutlineBox,
  IconName.Pencil,
  IconName.Plus,
  IconName.Reset,
  IconName.RunCookbook,
  IconName.Square,
  IconName.Table,
  IconName.TalkBubbles,
  IconName.Warning,
  IconName.WideArrowUp,
  IconName.WideArrowDown,
  IconName.WideArrowLeft,
  IconName.WideArrowRight,
];

export const fillIcons = [
  IconName.Bell,
  IconName.CheckList,
  IconName.DarkMoon,
  IconName.Database,
  IconName.HistoryClock,
  IconName.LightBulb,
  IconName.Lightning,
  IconName.MoonPromptTemplate,
  IconName.Ribbon,
  IconName.SolidBox,
  IconName.Spacesuit,
  IconName.Tools,
  IconName.OpenedBook,
  IconName.OpenedEmptyBook,
  IconName.Plug,
];

export const colorIcons = [IconName.Folder, IconName.FolderForChatSessions];
