export enum UserFlows {
  NewProject = '1',
  NewProjectWithNewTemplate = '2',
  NewProjectWithExistingTemplateAndResults = '3',
  NewProjectWithExistingTemplateAndRunNewTests = '4',
  NewProjectWithExistingTemplate = '5',
  NewProjectWithNewTemplateAndResults = '6',
  NewProjectWithNewTemplateAndRunNewTests = '7',
  EditExistingProject = '8',
  ViewTemplate = '9',
  EditExistingProjectWithResults = '10',
  NewTemplate = '11',
  NewProjectWithEditingExistingTemplate = '12',
  NewProjectWithEditingExistingTemplateAndResults = '13',
}
