apiVersion: v1
kind: ConfigMap
metadata:
  name: aiverify-portal-config
  namespace: dev
data:
  # portal env
  DB_HOST: aiverify-db-service.dev.svc.cluster.local
  DB_PORT: '27017'
  REDIS_URI: redis://aiverify-redis-service.dev.svc.cluster.local
  # api-gw env
  REDIS_HOST: aiverify-redis-service.dev.svc.cluster.local
  REDIS_PORT: '6379'
  TEST_ENGINE_URL: http://aiverify-test-engine-service.dev.svc.cluster.local:8080
  ALLOWED_ORIGINS: https://aiverify.eks-dev.aipo-imda.net
---
apiVersion: v1
kind: Service
metadata:
  name: aiverify-portal-service
  namespace: dev
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app.kubernetes.io/name: aiverify-portal
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aiverify-portal-deployment
  namespace: dev
  labels:
    app.kubernetes.io/name: aiverify-portal
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: aiverify-portal
  template:
    metadata:
      labels:
        app.kubernetes.io/name: aiverify-portal
    spec:
      serviceAccountName: default
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: aiverify-portal
          image: 052567997892.dkr.ecr.ap-southeast-1.amazonaws.com/aiverify-portal:0.10
          args:
            - "bash"
            - "-c"
            - "cd aiverify/ai-verify-apigw; node app.mjs & cd ../ai-verify-portal; npm run start"
          env:
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: password
          envFrom:
          - configMapRef:
              name: aiverify-portal-config
          resources:
            limits:
              cpu: 1000m
              memory: 2048Mi
            requests:
              cpu: 500m
              memory: 1024Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
                drop:
                  ["ALL"]
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: aiverify-shared-data
              mountPath: /app/aiverify/ai-verify-portal/plugins
              subPath: plugins
            - name: aiverify-shared-data
              mountPath: /app/aiverify/uploads/data
              subPath: data
            - name: aiverify-shared-data
              mountPath: /app/aiverify/uploads/model
              subPath: model
            - name: aiverify-shared-data
              mountPath: /app/aiverify/test-engine-app/logs
              subPath: logs
      volumes:
        - name: aiverify-shared-data
          persistentVolumeClaim:
            claimName: aiverify-shared-pvc
---