apiVersion: v1
kind: Service
metadata:
  name: fashion-mnist
  namespace: aiverify
spec:
  selector:
    app: fashion-mnist
  ports:
  - protocol: TCP
    port: 5001
    targetPort: 5001
---    
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fashion-mnist
  namespace: aiverify
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fashion-mnist
  template:
    metadata:
      labels:
        app: fashion-mnist
    spec:
      containers:
      - name: fashion-mnist
        image: fashion-mnist:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5001
        resources:
          limits:
            memory: "1Gi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "250m"
