import { RiFlaskFill, RiFlaskLine, RiUploadLine } from '@remixicon/react';
import Link from 'next/link';
import { UserFlows } from '@/app/userFlowsEnum';
import { Card } from '@/lib/components/Card';

type UrlSearchParams = {
  searchParams: {
    projectId: string;
    flow: UserFlows;
  };
};

export default function UserMenuPage(props: UrlSearchParams) {
  const { projectId, flow } = props.searchParams;

  if (!projectId || !flow) {
    throw new Error('Project ID and flow are required');
  }

  return (
    <main className="w-full px-6">
      <h1 className="mb-0 mt-6 text-2xl font-bold tracking-wide">
        Use Existing Test Results or Run New Tests
      </h1>
      <section className="mt-16 flex flex-wrap justify-center gap-10">
        <Link
          className="flex-1 basis-[350px]"
          href={`/results?flow=${UserFlows.NewProjectWithExistingTemplate}&projectId=${projectId}`}>
          <Card className="min-h-[250px] w-full cursor-pointer border-none bg-secondary-800 text-white hover:bg-secondary-700">
            <h3 className="mb-8 flex items-center gap-4 text-xl font-semibold text-white">
              <RiFlaskFill className="h-8 w-8 text-primary-500" />
              Use Existing Test Results
            </h3>
            <p className="mt-2 leading-6 text-white">
              Use existing test results that have already been uploaded to the
              system.
            </p>
          </Card>
        </Link>
        <Link
          className="flex-1 basis-[350px]"
          href={`/results/upload/zipfile?flow=${UserFlows.NewProjectWithExistingTemplate}&projectId=${projectId}`}>
          <Card className="min-h-[250px] w-full cursor-pointer border-none bg-secondary-800 text-white hover:bg-secondary-700">
            <h3 className="mb-8 flex items-center gap-4 text-xl font-semibold text-white">
              <RiUploadLine className="h-8 w-8 text-primary-500" />
              Upload Test Results
            </h3>
            <p className="mt-2 leading-6 text-white">
              Upload test results that was generated by external tools.
            </p>
          </Card>
        </Link>
        <Link
          className="flex-1 basis-[350px]"
          href={`/canvas?flow=${UserFlows.NewProjectWithExistingTemplate}&projectId=${projectId}`}>
          <Card className="min-h-[250px] w-full cursor-pointer border-none bg-secondary-800 text-white hover:bg-secondary-700">
            <h3 className="mb-8 flex items-center gap-4 text-xl font-semibold text-white">
              <RiFlaskLine className="h-8 w-8 text-primary-500" />
              Run New Tests
            </h3>
            <p className="mt-2 leading-6 text-white">
              Run new tests which are required by the report template.
            </p>
          </Card>
        </Link>
      </section>
    </main>
  );
}
