import {
  RiArrowLeftLine,
  RiFlaskFill,
  RiFlaskLine,
  RiUploadLine,
} from '@remixicon/react';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import { UserFlows } from '@/app/userFlowsEnum';
import { Button } from '@/lib/components/TremurButton';
import { Card } from '@/lib/components/TremurCard';
import { getProjects } from '@/lib/fetchApis/getProjects';

type UrlSearchParams = {
  searchParams: Promise<{
    projectId: string;
    flow: UserFlows;
  }>;
};

export default async function UserMenuPage(props: UrlSearchParams) {
  const searchParams = await props.searchParams;
  const { projectId, flow } = searchParams;
  const result = await getProjects({ ids: [projectId] });
  let updatedFlow = flow;
  if (flow === UserFlows.NewProjectWithNewTemplate) {
    updatedFlow = UserFlows.NewProjectWithNewTemplateAndRunNewTests;
  }

  if (!projectId || !flow || 'message' in result) {
    notFound();
  }

  return (
    <main className="w-full px-6">
      <h1 className="mb-0 mt-6 text-2xl font-bold tracking-wide">
        Use Existing Test Results or Run New Tests
      </h1>
      <section className="mt-16 flex flex-wrap justify-center gap-10">
        <Link
          className="flex-1 basis-[350px]"
          href={`/results?flow=${flow}&projectId=${projectId}`}>
          <Card className="min-h-[250px] w-full cursor-pointer border-none bg-secondary-800 text-white hover:bg-secondary-700">
            <h3 className="mb-8 flex items-center gap-4 text-xl font-semibold text-white">
              <RiFlaskFill className="h-8 w-8 text-primary-500" />
              Use Existing Test Results
            </h3>
            <p className="mt-2 leading-6 text-white">
              Use existing test results that are already available in the
              system.
            </p>
          </Card>
        </Link>
        <Link
          className="flex-1 basis-[350px]"
          href={`/results/upload/zipfile?flow=${flow}&projectId=${projectId}`}>
          <Card className="min-h-[250px] w-full cursor-pointer border-none bg-secondary-800 text-white hover:bg-secondary-700">
            <h3 className="mb-8 flex items-center gap-4 text-xl font-semibold text-white">
              <RiUploadLine className="h-8 w-8 text-primary-500" />
              Upload Test Results
            </h3>
            <p className="mt-2 leading-6 text-white">
              Upload test results that was generated by external tools.
            </p>
          </Card>
        </Link>
        <Link
          className="flex-1 basis-[350px]"
          href={`/canvas?flow=${updatedFlow}&projectId=${projectId}`}>
          <Card className="min-h-[250px] w-full cursor-pointer border-none bg-secondary-800 text-white hover:bg-secondary-700">
            <h3 className="mb-8 flex items-center gap-4 text-xl font-semibold text-white">
              <RiFlaskLine className="h-8 w-8 text-primary-500" />
              Run New Tests
            </h3>
            <p className="mt-2 leading-6 text-white">
              Run new tests which are required by the report template.
            </p>
          </Card>
        </Link>
      </section>
      {flow !== undefined && flow !== UserFlows.EditExistingProject ? (
        <section className="mt-[200px] flex items-center justify-start gap-4">
          <Link href={`/templates?flow=${flow}&projectId=${projectId}`}>
            <Button
              className="w-[130px] gap-4 p-2 text-white"
              variant="secondary">
              <RiArrowLeftLine /> Back
            </Button>
          </Link>
        </section>
      ) : null}
    </main>
  );
}
