apiVersion: v1
kind: Service
metadata:
  name: donation-predictor-service
  namespace: aiverify
spec:
  selector:
    app: donation-predictor
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
---    
apiVersion: apps/v1
kind: Deployment
metadata:
  name: donation-predictor
  namespace: aiverify
spec:
  replicas: 1
  selector:
    matchLabels:
      app: donation-predictor
  template:
    metadata:
      labels:
        app: donation-predictor
    spec:
      containers:
      - name: donation-predictor
        image: donation-predictor:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "250m"
