
name: v2 Docker Build (EC2)

env:
  # Images to build
  IMAGE_NAMES:  'aiverify-apigw,
                 aiverify-portal,
                 aiverify-test-engine-worker'

  GITHUB_TOKEN: ${{ github.token }}
  
on:

  # Run this workflow manually from Actions tab
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch or tag to checkout'
        required: true
        default: 'main'
        type: string
      image_to_build:
        description: 'Name of image to build'
        required: true
        default: 'aiverify-apigw'
      image_tag:
        description: 'Tag for the image, e.g. 2.0.2'
        required: false
      build_base:
        description: 'Build aiverify-python-base image'
        required: false
        default: 'true'

#   push:
#     branches: [ ci/use-remote-server ]


# Allow one concurrent deployment
concurrency:
  group: ${{ github.repository }}-${{ github.workflow }}
  cancel-in-progress: true


jobs:
  build-and-push:
    runs-on: self-hosted
    permissions:
      id-token: write
      contents: read
      packages: write

    steps:
      # Check out the source code from the specified branch
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch || 'main' }}
     
        # Free up disk space before building large Docker images
      - name: Free up disk space
        run: |
          bash .ci/free_disk_space.sh

      - name: Build images
        run: |
          chmod +x .ci/ec2_docker_build.sh
          .ci/ec2_docker_build.sh
