export const config = {
  "principle": "Transparency",
  "description": "Transparency provides visibility to the intended use and impact of the AI system. It complements existing privacy and data governance measures. Integrating transparency into the AI lifecycle helps ameliorate the problems caused by opaqueness. The testable criteria focuses on ensuring communication mechanisms are in place to enable those affected by AI systems to understand how their data is collected and used, as well as the intended use and limitations of the AI system. This should be done in a manner appropriate to the use case at hand and accessible to the audience.  ",
  "sections": [
    {
      "section": "Transparency",
      "testType": "process-checklist",
      "checklist": [
        {
          "testableCriteria": "Provide the necessary information to end users about the use of their personal data to ensure it is processed in a fair and transparent manner",
          "processes": [
            {
              "pid": "1.1.1",
              "process": "Align with (1) the PDPC’s Advisory Guidelines on Key Concepts in the PDPA; (2) Guide to Accountability; and (3) Guide to Data Protection Impact Assessments",
              "metric": "Internal documentation (e.g., policy document)",
              "processChecks": "Documentary evidence of internal policy requiring alignment with existing data protection laws and regulations, which include:  <br/>(in Singapore)<br/>- PDPC’s Advisory Guidelines on Key Concepts in the PDPA; <br/>- Guide to Accountability; and<br/>- Guide to Data Protection Impact Assessments.<br/>(outside Singapore)<br/>- Applicable data protection laws/regulations"
            },
            {
              "pid": "1.1.2",
              "process": "Publish a privacy policy on your organization’s website to share information about the use of personal data in the AI system (e.g., data practices, and decision-making processes). The general disclosure notice could include:<br/>– Disclosure of third-party engagement<br/>– Definition of data ownership and portability<br/>– Depiction of the data flow and identify any leakages<br/>– Identification of standards the company is compliant with as assurance to customers",
              "metric": "External / internal correspondence",
              "processChecks": "Documentary evidence of a privacy policy on your organization’s website to share information about the use of personal data in the AI system (e.g., data practices and decision-making processes). <br/><br/>The general disclosure notice could include:<br/>– Disclosure of third-party engagement; <br/>– Definition of data ownership and portability;<br/>– Depiction of the data flow and identify any leakages; and<br/>– Identification of standards the company is compliant with as assurance to customers"
            }
          ]
        },
        {
          "testableCriteria": "Where possible (e.g., not compromising IP, safety, or system integrity), identify appropriate junctures in the AI lifecycle to inform end users and/or subjects about the purpose, criteria, limitations, and risks of the decision(s) generated by the AI system in an accessible manner",
          "processes": [
            {
              "pid": "1.2.1",
              "process": "Design an in-house policy on communication to consumers that articulates the principles for transparency, e.g., define the purpose and context of communication to determine how and what to communicate",
              "metric": "Internal documentation (e.g., policy document)",
              "processChecks": "Documentary evidence of an in-house policy on communication to consumers that articulates the principles for transparency, e.g., define the purpose and context of communication to determine how and what to communicate"
            },
            {
              "pid": "1.2.2",
              "process": "Inform relevant stakeholders that AI is used in your products and/or services",
              "metric": "External / internal correspondence",
              "processChecks": "Documentary evidence of communication to relevant stakeholders that AI is used in the organisation's products and/or services"
            },
            {
              "pid": "1.2.3",
              "process": "For decisions made by the AI system, where possible, communicate to end users the factors leading to the decision e.g., \"You are being shown this product because you bought this item.\"",
              "metric": "External / internal correspondence",
              "processChecks": "Documentary evidence of communicating to end users the factors that lead to decisions made by AI systems"
            },
            {
              "pid": "1.2.4",
              "process": "Consult end users at the earliest stages of AI system development to communicate how the technology is used and how it will be deployed",
              "metric": "External / internal correspondence",
              "processChecks": "Documentary evidence of communication with end users at early stages of AI system development concerning how the technology is used and how it will be deployed"
            },
            {
              "pid": "1.2.5",
              "process": "Surface relevant information regarding accuracy, intended use cases, and limitations of the AI system, including the risk assessment, to end users",
              "metric": "External / internal correspondence",
              "processChecks": "Documentary evidence of communication with end users concerning the AI system, which includes (where applicable): <br/><br/>- accuracy;<br/>- confidence scores;<br/>- intended use cases;<br/>- limitations; and<br/>- risk assessment"
            }
          ]
        },
        {
          "testableCriteria": "Provide information to guide end users on the proper use of the AI system in an accessible manner",
          "processes": [
            {
              "pid": "1.3.1",
              "process": "Provide information such as the purpose, intended use and intended response of the AI system to end users",
              "metric": "External / internal correspondence",
              "processChecks": "Documentary evidence of communication with end users concerning the intended use and intended response of the AI system (e.g., Model Card and Data Card)"
            }
          ]
        }
      ]
    }
  ],
  "summaryYes": "Company has put in place communication mechanisms to enable those using and/or affected by the AI system to understand how their data is collected and used, and the intended use and limitations of the AI system.",
  "summaryNotYes": "Company should review if the current communication mechanisms in place are sufficient to enable those using and/or affected by the AI system to understand how their data is collected and used, and the intended use and limitations of the AI system.",
  "recommendation": "Company can consider consulting the users of or individuals affected by the AI system to find out if the current level of information provided to them is adequate, and if not, to address the information gap accordingly."
}